# Generated by Django 3.1.6 on 2021-03-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactMessage',
        ),
    ]
