# Generated by Django 3.1.6 on 2021-03-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210303_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='in_favorite',
            new_name='in_favourite',
        ),
    ]
