# Generated by Django 3.1.6 on 2021-03-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210310_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_favourite',
        ),
    ]
